### ISSUE TITLE
Improve Alignment Panel UX

### ISSUE THREAD

**Issue by Alecaddd** [akiraux/Akira#135]
The current alignment panel is a good start but it needs a few improvements.

- Make the tooltips translatable
- Make the alignment grid expand with homogeneous columns to follow the resizing of the left panel
- Implement Granite accelerators (Suggestions for key stroke combinations?)

**Comment by giacomoalbe** [comment]
Ok I can take care of those things, if you want :)

* Ok for the tooltips
* In the beginning I created a Gtk.Grid inside another Grid just to kee all the buttons centered in the row, because otherwise I thought that it would have been difficult to find them in the side bar was very large. The desidered behaviour is to have them span across the entire with of the side bar, right? 
* Ok for accelerators. I bound those actions (well actually only `center-vertical` and `center-horizontal`) in Inkscape with `CTRL-H` and `CTRL-V`. I replaced paste command with `C-S-V`. But maybe `C-S` might be a good prefix for alignment to keep consistency with other application when it comes to copy pasting. 
 This is my proposal:
  * `C-S-V`: Center vertically
  * `C-S-H`: Center horizontally
  * `C-S-L`: Align left edges
  * `C-S-R`: Align right edges
  * `C-S-T`: Align top edges
  * `C-S-B`: Align bottom edges
  * `C-S- -`: Distribute centers horizontally
  * `C-S- |`: Distribute centers vertically

**Comment by Alecaddd** [comment]
>  The desidered behaviour is to have them span across the entire with of the side bar, right?

Correct. The left panel, even if resizable, will most likely remain pretty tight as it won't need to visualize long strings of text like the layers panel. We control all the widgets in there and the resize action is mostly to accommodate for other languages.
A wide left panel where the alignment buttons are really far between each other is a pretty remote edge case.

**Accelerators**

I want to avoid touching pre-existing or commonly used key stroke combinations like `Ctrl + V` or `Ctrl + Shift + V`.
Also, this panel is particular as we have 8 actions all in line with different names, and I feel like it will be hard to remember those key strokes based on names, especially since those names change based on the language.

What about a combination of `CTRL + SHIFT + numbers from 1 to 8`? In this way, the numbers will respect the order of the icons on the panel, and remembering a number is easier than remembering a letter.

As last thing, let's simplify the tooltips:
* Distribute Horizontally
* Distribute Vertically
* Align Left
* Align Center
* Align Right
* Align Top
* Align Middle
* Align Bottom

**Comment by giacomoalbe** [comment]
I've created a PR for this! 

Have a look at it, it should be easily mergeable since it does not break anything and it has been pulled from current master. 

IDK if the translation method is correct, since I was not able to test it properly.

I run the `ninja pot` and `ninja update-po` commands, labels where added to the po files - which I didn't commit with the rest, of course - but then I haven't been able to change language and see whether strings where translated or not. 

I would be nice to open an issue to help the translation process to happen, what do you think?

**Comment by Alecaddd** [comment]
Thanks for the PR, I'll review later.
Better avoid getting into translations or asking other users to contribute as lots of changes and updates are expected to the app and we can't guarantee a string freeze. It would be annoying for contributors to keep fixing their translations because we move stuff around.
Once the app is close to release, we will announce a string freeze and ask for translators.

**Comment by Alecaddd** [comment]
Closed by  #146
