### ISSUE TITLE
Schema settings change unexpectedly 

### ISSUE THREAD

**Issue by Alecaddd** [akiraux/Akira#136]
The Schema Settings related to `window-height` and `left-panel` keep changing every time the window gets closed even if the user didn't resize those elements.

**Left Panel**
It keeps resetting to 347px width only if the user resizes the panel to be smaller than that value. It doesn't happen if the panel is larger than 347px

**Window Height**
The height of the window increases by 12px at every restart.

**Comment by bilelmoussaoui** [comment]
I don't think we should save the window width and height on gsettings, it shouldn't be the app itself that save that info and restore the same width/height.

Otherwise, we could listen to whenever the widget changes its width/height and store that. In order to restore the same workflow that the user set up before closing the app, we should store a lot of info and we might need to figure out a better to do that (if there are any)

**Comment by Alecaddd** [comment]
I think the gsettings approach it's OK since we're not storing a few value. 
So far, we're saving on destroy:
* Windows size and location
* Dark/light theme
* Icon style
* Labels ON/OFF
* Panels' size

All the other settings would be saved on a per file based system, since are not global settings.

What other method would your suggest to use instead of gsettings?

**Comment by bilelmoussaoui** [comment]
I don't really have any method on the mind, I just asked the question in case someone could help with that. I'm going to give it a look and improve the situation a bit for now.
