### ISSUE TITLE
Icon for dev build

### ISSUE THREAD

**Issue by raggesilver** [akiraux/Akira#143]
## Expected Behavior

A icon that can be recognized as being Akira's but that also differs from the original (stable) version.

## Possible Solution

Many apps, Firefox for example, achieve this by simply changing the icon's colors. This is simple but effective.

An example of what Akira's icon could look with different colors:
![](https://raw.githubusercontent.com/raggesilver/Akira/b70e783012d64d6742164407cce38b8a8aef0a24/data/icons/128x128/com.github.akiraux.akira.svg?sanitize=true)

As an addition, I would like to suggest that `.svg` files were stored in a more intuitive path, like `data/icons/scalable`

**Comment by Alecaddd** [comment]
I like the purple variation, I think it's a good choice and it's largely used in development related sites.
I'm not sure it matches properly with the dark circle. Would you be able to create some variations with a lighter gradient underneath, or a tint different from the original icon?

We're not gonna update the file path because we're offering pixel hinted icons. Even if the vector SVG is scalable, using an icon created at 128px for a 48px resolution, or vice-versa, will not look good at all.

**Comment by raggesilver** [comment]
Changing the shadow to a lighter color with the original background gradient:
![](https://raw.githubusercontent.com/raggesilver/Akira/93a6f77f67a8512828acc2e858931640668367ec/data/icons/128x128/com.github.akiraux.akira.svg?sanitize=true)

Changing the background gradient with the original shadow:
![](https://raw.githubusercontent.com/raggesilver/Akira/e074c62a0fa659e525849c6183489391818310bb/data/icons/128x128/com.github.akiraux.akira.svg?sanitize=true)

**Comment by Alecaddd** [comment]
I was thinking about something like this
![dev-icon-test](https://user-images.githubusercontent.com/2527103/56464520-6613c680-63a0-11e9-908e-2ea59f50a6f8.png)

I like the bright background which it clearly separates this version from the main icon, but now the purple is a bit too bright and it doesn't blend properly. it needs a bit of tweaking.
