### ISSUE TITLE
[Docs] Add contributor guide to project

### ISSUE THREAD

**Issue by nisrulz** [akiraux/Akira#167]
Suggestion: A single page/wiki page that enlists all the links and sets the starting point for contributors for this project.

Would possibly have links and description about:
- How to set up the dev build
- Vala primer
- Links to videos
- Github repo and some examples
- Links to chatrooms
... more?
> I can open the PR with few links related to Vala programming but would like to accumulate other sources such as Riot chatroom links, Discourse links, etc

**Comment by albfan** [comment]
Hi,

We understand the suggestion and we are preparing #150 for it, but in general there's no point in Akira to collect all that info when there's a wiki in GNOME aimed to that: 

It will guide you through gtk, flatpak, GNOME Builder and starter projects to learn gtk.
 
There's too a really good tutorial for vala:

- https://wiki.gnome.org/Projects/Vala/Tutorial

that should get you started. We would get outdated real soon if we start an initive similar to that.

About chat rooms, we don't have any specific for akira, but you can find us on gimpnet (IRC) or its matrix bridge: https://wiki.gnome.org/Newcomers/ to ask general questions about development in gtk (which is the base for Akira development)

**Comment by nisrulz** [comment]
Got it. Thanks :)

However, I meant more on the same lines as yours. Just making it easier for people to know where to start. Here is an example.

---

# Contributions
- Akira is written in Vala language.
- To start learning how to program in Vala, check out the [official tutorial](https://wiki.gnome.org/Projects/Vala/Tutorial)
- To ask general questions about development in GTK, head over to [this link](https://wiki.gnome.org/Newcomers/)
- Find some hacking tips for Akira here.

**Comment by nisrulz** [comment]
Since we are talking about adding a contribution guideline, has [Gitter](https://gitter.im/home/explore#createcommunity) been considered to be able to reach out the devs quickly?

**Comment by bilelmoussaoui** [comment]
@nisrulz I think if we will ever use something, it wouldn't be Gitter. I used Gitter before, it's not that great :/ Using Matrix or just IRC would be pretty fine.

**Comment by nisrulz** [comment]
Is there a specifically named channel for Akira that I am not able to find? 🤔

**Comment by nisrulz** [comment]
Is this where the core devs for Akira discuss everything? 

https://riot.im/app/#/room/#_gimpnet_#gtk:gnome.org

**Comment by bilelmoussaoui** [comment]
@nisrulz Me and @albfan hang a lot on GNOME/GTK chatrooms but they are not related to Akira. We have a private Slack for the four of us. I will take care of the Akira public chat room.

**Comment by nisrulz** [comment]
Oh ok. It would be nice to have a public chat room where people can talk about Akira. There always questions and opening issues to ask those is a bit unwanted for the project and the developers alike.

I appreciate your response, though. I am trying out Akira and in the process mentioning what any newcomer to the project might ask about.

**Comment by Alecaddd** [comment]
We also have a Discord, but that's only for Patreon supporters, accessible for ever with a simple $1 donation. Even if you donate once you'll retain access to it.
I don't think we will open a dedicated public chat room for now as we're super small and working on it part-time, so our time is super limited.

**Comment by nisrulz** [comment]
Thank you for your response @Alecaddd   

However, I don't quite get your point.  It makes sense to me that the team of Akira would ask donations from people who want to help make Akira come to life from being just a mockup.  So the users who are interested and do not contribute back in any other form will be supporting the project via donations.  That is all good and I am all in for it. In fact, I have donation links up on each of my open source repositories. That is the least support we can ask for the effort open source maintainer put into the project.

The point which I don't quite get is that the Discord channel is only accessible to people once someone back up the project with money which being generic, means even developers. Developers, who contribute back to the project with their own time, effort and contributions have to now also pay for getting access to a simple chat room to talk directly to the core team of Akira?

What this will do is, stop a  lot of developers from contributing back to Akira. On the other hand, the core team of Akira is probably not considering the consequences of this move, like the below:
1. Someone is going to start their own slack/discord channel and maintain a community there. This will reflect poorly on the core team itself that they being available only behind a paywall.

1. First-time contributors who want to help the project in any form be it in terms of code/documentation/testing and have questions will simply open issues for questions. Your issue tracker will be full of questions once the project hits the version 1.0. Which means the core team is taking care of all this when their focus should be mostly on the core issues.

1. As of now the core team and a small group of individuals are answering questions. If the chat room was public, more people would jump in and the core team only needs to jump in if something very specific is being asked and only someone experienced can answer that.  The community being built around an open source project is mostly the driving force for its success. You can take an example from any successful open source project.

I am open to hearing your thoughts.

**Comment by Alecaddd** [comment]
Thank for expressing your point of view.
As I said, the main reason is because we're busy and we don't have time. Here's a quick list of reasons of the whys behind this decision.

* A discord for paying users is an incentive to gather donation, giving a sort of VIP treatment to users willing to financially support the project. That's it, there's no hidden meaning of "we don't consider contributors and other devs worth it".
* Publicly opening a chat room for everyone to sign up will open a direct communication channel for all those users that aren't either contributors or supporters. We don't have time to deal with trolls, or a too big of a community to answer everyone.
* Instant messaging platforms are often abused and overused, increasing disruption and negatively affecting developers. Keeping it small and manageable since this is not our full time job is vital for our mental sanity.
* GitHub is for devs, issues are for devs, and dev related discussions should stay here. This very own issue thread is a great example why it works. If you had written this message in discord it would have gotten lost behind hundreds of other messages and I wouldn't have had the chance to answer. Being here, in an issue, gives me the ability to come after a week, easily read it, easily answer it, and keep the conversation on topic.
* Regular users asking random question already happen daily on social media, that's why we have a Twitter and a Mastodon account. Regular users don't often open issues to simply ask questions, and since the beginning of the project probably only 5 of the 100 opened issues were random questions without any dev related point.
* Having a community where the core team doesn't answer and let users take care of each other is pretty bad for a project that doesn't exist. Once we release a first usable version, we will open a publicly accessible discord channel.

To quickly answer your points

> Someone is going to start their own slack/discord channel and maintain a community there.

I don't really see the problem since Akira is open source and people can literally fork it and create a variation of it. Having multiple Akira-focused communities managed by other users sounds more like a win.

> First-time contributors who want to help the project in any form be it in terms of code/documentation/testing and have questions will simply open issues for questions.

Good, that's what they should do. Having a contributing guide, a well written wiki, and the website with good resources will lower the entry barrier, but even so, I prefer having new devs asking questions on GitHub instead of a messaging board.

Managing issues is not a burden, it's part of maintaining an open source project, and having 300 messages a day on GitHub is better than 300 messages a day on Discord.

**Comment by nisrulz** [comment]
Thank you @Alecaddd for taking the time to answer my concerns and questions. Highly appreciate it. 

I now get your stance for keeping it the way it is and respect that completely. 

These questions will popup up in future too and I think this issue in itself is a good record to redirect people since not everyone will look at the this the way you do from a project maintainers perspective. 

Every project is entitled to their own way of working and that is the beauty of open source.  This is interesting for me to see more possibilities of how projects are managed.

Hoping to start contributing with code/issues soon to Akira.

Thank you once again!

**Comment by bilelmoussaoui** [comment]
This can be closed now?

**Comment by nisrulz** [comment]
I think so, yes. Closing now.
