### ISSUE TITLE
Consider adding a menubar.

### ISSUE THREAD

**Issue by ripefig** [akiraux/Akira#195]
Lots of people are used to having a menubar in complex applications.

It is very helpful for complex applications for a few reasons:

1. If users want to find stuff, they know where to look: the menubar always serves as a standard entry point to explore all the features of the program. If you spread out the functionality across many buttons, popovers and context menus, users will have search through your entire application with no roadmap. An action could be literally anywhere on the screen - or it could be hidden in another screen/context menu.
2. You get a system HUD for free, which allows users to search through menu items by typing. Programs like GIMP and LibreOffice benefit a lot from this, and it is a standard feature on Mac and Unity. Currently KDE is developing their own HUD for Plasma Desktop. The system HUD is brought up time and time again by users as one of the most desirable features. If you use Gmenu and have a menubar, your app gets a HUD for free.
3. You get a global menu for free (on KDE etc.). With a global menu, your app will look like it does now but it will also have menubar drawn by the desktop.
4. If you make some design decisions that users don't like (e.g. putting a button where they can find it), the menubar will help cushion the blow. It serves as an insurance policy in case your main UI doesn't work right for some users. This is standard on Mac OS, for example - modern Mac apps look just like Gnome apps but they also have menubars and it's a flexible model that works very well for them.
5.  The menubar interface is the standard outside Gnome/Elementary amd mobile apps, and consistency with other applications is preferable to inconsistency. Even if your UI is designed well, inconsistency between apps will result in a poorer user experience.

I therefore strongly repeating your app functionality in a menubar. Probably, you wouldn't want show the menubar on Elementary OS but everywhere else it could be really helpful.

**Comment by albfan** [comment]
we do have a menubar. I think better than a menu bar we need an action shortcut to call any possible available action (Ctrl+Shift+A type action name)

But for a design app, a bloated menu with any possible action (or even worst a dynamic menu with actions that come and go depending on canvas state is counterintuitive)

What's the actual problem you see this menu bar will solve?

See there's a GNOME initiative to remove menu bars

https://gitlab.gnome.org/GNOME/Initiatives/wikis/App-Menu-Retirement

**Comment by ripefig** [comment]
I know about the Gnome initiatives and it's fine to follow them *on Gnome* (actually you can't follow Gnome HIG, since you're using Granite but that's another story.) So yeah, I am not saying use the menu bar on Gnome desktop. But I'd like to see a menubar on KDE - you don't even have to draw it inside your app, you can just have the DE draw a global menu for you thanks to GMenu.

But you have to consider the fact that almost nobody is following their guidelines, including the big GTK applications like Evolution, Gimp and Inkscape. In fact, it's really hard to even imagine these apps without menubars. Same goes for their other initiatives, like removing tray icons. The point of a guideline is to set a standard and Gnome's guidelines are failing in that respect - they are just going against the de facto Palo Alto standard without replacing it and this results in an incoherent UI for users.

> What's the actual problem you see this menu bar will solve?

I am not intimately familiar with your app so I can't be specific, but I have used similar software online without a menubar (see Figma for example). It was very hard for me to find my way around. Maybe the UI isn't that bad but I just don't know where anything is because I am used to having a standard entrypoint from which to explore the entire application. The problem with Gnome/EOS/Web apps is that that they don't have such an entry point. Instead they smear the functionality over several screens and each app does this in its own special way. The end result is a bigger learning curve if the app is complex, since you don't know where to look.

Look at all other software, including professional software. They all use menubars (or ribbons, which is the same thing). Mac OS apps use "headerbars too" but they also use menubars to expose the application in a standard, efficient way.  It's a proven interface for thousands of major applications. I think the burden of proof is clearly on Gnome here. There are no programs with lots of tools that don't use menubars/ribbons, so Gnome's HIG hasn't proven itself yet. They point to browsers, but I personally have a hard time even using Chrome's hamburger menu, despite having used Chrome for many years.

A menubar will allow your app to integrate much better into desktops like KDE and XFCE, and it will help expose functionality for users who are accustomed to a traditional interface.


> But for a design app, a bloated menu with any possible action (or even worst a dynamic menu with actions that come and go depending on canvas state is counterintuitive)

Photoshop menus are pretty extensive, for example. Given the number of tools PS has, it needs a large menu hierarchy. Luckily the menubar is compact, so it's not going to crowd out the main UI at all. But I agree that dynamic menus are are a terrible idea.

>  available action (Ctrl+Shift+A type action name)

Well yeah you could code your own HUD or you could **get one for free** thanks to menu export over DBus. And having the desktop provide the HUD has the advantage of being standardized across apps. I always forget the shortcuts for the app-specific command palettes ... in one app it's Ctrl+Shift+P, in another Ctrl+Shift+A, in another it's Alt+Space etc. For the central Unity-type HUD, I just press `Alt` everywhere and start typing.

**Comment by Alecaddd** [comment]
Hi, thank you so much for your interest in Akira and your comment.

For now, our main goal is to develop an application for elementary OS, following its HIG.
The goal of Akira, and all the work we're doing on the interface, is to offer an intuitive and easy to learn application that doesn't require going around menus looking for the tool you need.

Being used to finding your way around by reading every single item of the menubar doesn't automatically imply that that's the proper way of doing things.

I'm a professional UX designer, and I've been working with others for many years with software like Sketch and Figma. Not a single one of my colleagues uses menu bars, even in Sketch, because the UI offers proper solutions in a sane and intuitive context.

The main goal of Akira is to remain easy to use and intuitive to learn, without bloated features scattered or hidden around the interface. The app will adapt to the user's actions offering the proper tools in the correct context.

:: Devil's advocate mode ::
With that said, it's impossible at this stage to say "this is the only truth!", because none of us know at this point.
We know that a bloated menu like Photoshop is not intuitive and confusing.
We know that we want to offer a clan and simple interface for vector design.
We know we want to provide a tool that will empower users to create something from the first opening.

We're not against changing our mind, reconsidering our solutions, or scrapping ideas if better solutions come.
One of my side project is to launch a usability study once the first version of Akira is out.
We want to learn from the users, and see if our ideas and solutions are actually working and are better/more intuitive than what's considered the "standard approach".

**Comment by ripefig** [comment]
Well sure but Sketch still has a fairly large menu, doesn't it? I don't think they could get rid of it without seriously compromising their UI. And I would trust the design patterns of professional desktop software over Gnome/Elementary HIG, simply because the latter hasn't produced much beyond very rudimentary single-purpose apps.

So if your goal is Sketch for Linux, a menubar seems logical.

Ofc experienced users don't need menus *as much* because they've already learned where everything is and use a lot of shortcuts. 

> without bloated features scattered

It is a question of how many features you want in the app then. If you have a very simple app, like most modern EoS apps, then you don't need a menubar. But the more capabilities you gain, the harder it is to avoid something like a menubar or a ribbon, and Gnome/EoS HIG allows for neither. Again, I know of no featureful desktop apps that manage avoid menubars or ribbons. I think there is a reason for it. 

Having a menubar doesn't mean you can't have all the contextual tools and fanciness you want. In fact, it gives you a more freedom, since you don't have to integrate literally everything into the main UI and a couple of hamburger menus.

Perhaps in the future you'd want to make Akira integrate better with other DE's - after all very few people use EoS. And for that it would help to have a menubar.

**Comment by Alecaddd** [comment]
Now we're shifting the focus from a menubar to a OS integration?
Akira will also ship as flatpak, snap, and appimage, so you can use it wherever you want.

Once again:
* Having a menubar at this stage doesn't make sense at all due to the simple initial release and amount of features.
* We're aiming for an adaptive UI that helps the user, flattens the learning curve, and prevents the usual question "Where is the button now?"
* Once a first release is out, we will gather feedback, do some research, and carefully evaluate next steps.

**Comment by ripefig** [comment]
> Having a menubar at this stage doesn't make sense at all due to the simple initial release and amount of features.

Fair enough.

**Comment by lestcape** [comment]
> The goal of Akira, and all the work we're doing on the interface, is to offer an intuitive and easy to learn application...

If you really want to give to the user an intuitive and easy to learn application you should considered follow all the available desktop HIG. That means, you should implemented several visualization for your application and use one of it depending of the desk on where the user is. An application can be see as non-intuitive, if is displaying his components in a different way of how others most commons applications are displayed. To me, be congruent with the user workflow is the most natural and easy way to be intuitive and easy to use. But, I'm not saying that you should support all the desktop HIG, my point is just that to me be intuitive and easy to learn is really a relative thing that **should not** be use an as excuse never. 

I'm **NOT** a professional UX designer. I'm just a user that want to learn less and use more applications. Fortunately, I'm not the only one that think that it's important follow the same HIG, because this is the reason of why GNOME core applications have a lot of forks. For example: The Mate forks and the Cinnamon XApps.

**Comment by albfan** [comment]
We understand the concern and the arguments. Right now this is not actionable, but prevention if our goal to be intuitive and simple fail.

Thanks for sharing your view, we care about be agnostic if that spread the use of Akira, but we can always open a detailed issue when that happens.
