### ISSUE TITLE
Split the Canvas

### ISSUE THREAD

**Issue by Alecaddd** [akiraux/Akira#229]
The `Canvas.vala` file is growing exponentially at every PR. Since that's the main core of our application, we should define how to divide it into multiple classes in order to keep our core library as scalable and modular as possible.

Let's throw a bunch of ideas on how to approach this, and open some draft PRs to prototype solutions.

**Comment by giacomoalbe** [comment]
I thought about a possible Canvas workflow, just to split each functionality to its own module or "manager". 

I will keep the actual behaviour of the Canvas module as a "state machine" holder, which each state defined by a different `EditMode` (`INSERT`, `SELECTION`, `PAN`, `ZOOM`, `MULTI_SELECT`, more_to_follow). 

The Canvas itself is responsible for receiving inputs (mouse, keyboard) and to dispatch them to the corresponding manager, according to the current state of the canvas itself. 
Another responsability of the canvas module is to be the "glue" between all those different piece of code, so, practically speacking, to issue the correct commands to the managers in the correct order. 

Let's start with an example, just to clarify a little bit more how is the overall process working: 

## CASE: User creates an object

* The user clicks 'R' on the keyboard. The Canvas itself has focus, so the event gets dispached to the `key_press_event`. 
* Here, based on the current state (which, by default, is `SELECTION`), the Canvas acts differently. In this case (state `SELECTION`), it changes its state to `INSERT` and updates its `insert_item_type` variable to _rectangle_ (which is the shape associated with 'R').
* The cursor changes (this action is resposibility of the Canvas itself, or we can create just another Manager and send him the message to change the cursor through the EventBus). 
* Then the user clicks on the canvas. The event is received and passed to the `button_press_event`, which, based on the state (`INSERT`) does the following things: calls the `add_item` function of the ItemsManager, which creates a new object and renders it to the Canvas. After that, this newly created item is added to the SelectedBoundManager (which has the responsability to handle all the selected items and to apply transformations on them according to the SelectedItemsBound) and the BOTTOM_RIGHT nob is set selected). 
* The user now moves the cursor. The canvas receive the event which is passed to the "motion_notify_event" that, again based on the state (`INSERT`) passes the event coordinates to the SelectedItemsBound which is responsible for growing the `selected_bound' and, in turns, updates the size (width and height) of every selected item (in this case just one, the newly created object). 
* The user releases the mouse. The event gets passed to the SelectedItemsBound, which simply stops the growth of the newly created object. The canvas changes its state to `SELECTION`. The cursor changes accordingly.

Here, each of those _managers_ or _delegates_ (SelectedItemsBound, ItemsManager, CanvasState, Align, Snap, Nob, ect) shares the same canvas instance, which is passed to them in the construct method of the canvas. 

The communication between them and with the other elements of the UI (the headerbar, the sidebar, the properties panel, the fillpanel, etc) happens through the EventBus object.

Here we can create an utility class called EventParams, which can be a sort of dynamic HashMap that can contain an arbitrary number of named arguments and can be used to pass data around (currently, EventBus can pass to signals only one param of type string, which might not be enough and might cause some confusion when we need to understand what has been passed between two elements with a signal just by looking at the code).

With this system in place, we can also have multiple selectable objects from the beginning, since the SelectedItemsBound is responsible for handling affine trasformations of his objects (by scaling, rotatin and moving relative to its center of mass and propagating those changes to its children - the selected items - according to the relative position between the center of the objects and the center of the selected_bound) and, at the same time, NobManager simply needs to draw its children (the nobs) around the selected_bound, regardless of the amount of objects selected. 
The header bar could listen to the "item_added_to_selection" (or whatever name we choose) event of SelectedItemsBound to retrive the number of selected items and change the icon visibility accordingly. 
The same could be done by the AlignItems panel and the FillItem panel, they can both listen for those kinds of event and act accordingly. 

In the end, we can have different Models for the Canvas items, in order to abstract the Goo.CanvasItem to suit our needs better. In particular we can create a "root" model class that has all the common properties we need for our items, like width, height, x, y, transform, border, border_color, background_color, z-order, id, ecc and then extend this class to accomodate for the different objects we'll have in the canvas, like Rectangle, Ellipse, Text, Artboard, Group, Image, etc, adding the specific fields that differenciate those elements. 

I also have some ideas on how to apply affine transformations to multiple selected objects. By looking at how Inkscape does this task, I discovered that scaling, rotating and moving are always relative to a "pivot" point, that depends on which nob are you selecting (in general is the point opposite to the grabbing handle). So by simply defining a `rotate_around`, `scale_around` and `move` function, on the SelectedItemsBound object we can achieve the desidered result (in the end it's simply a matter of composing different transformations, like translate_to_center, scale, translate_back, the same for rotation). 
We could also have an AffineTransformationManager, which would be responsible for calculating the _amount_ of the transform and its direction and then to apply it according to the center of the selected_bound to every selected item. This way, we can limit the responsabilities of each piece of code even more (SelectedItemsBound is only responsible of calculating the bound and to keep track of which item is selected whereas AffineTransformManager calculates the trasformations and applies them to the selected items). 

I think I'm going to make a tiny prototype of this overall thing in order to see wheater it's technically feasible and developer friendly as I expect it to be. 

Moreover, if you need more "use case" to understand how the system "works", just ask and I'll provide other examples. 

I'd like to receive some feedback on the idea, so feel free to share your thoughts about it :)

**Comment by Alecaddd** [comment]
Overall I think this is the right approach. Just a couple of notes on a few points:

> Here we can create an utility class called EventParams, which can be a sort of dynamic HashMap that can contain an arbitrary number of named arguments and can be used to pass data around (currently, EventBus can pass to signals only one param of type string, which might not be enough and might cause some confusion when we need to understand what has been passed between two elements with a signal just by looking at the code).

Indeed, the EventBus as it is right now feels a bit limited and on the path to grow exponentially at every iteration.
I wonder if we could update it to be a bit more smart, and instead of manually writing each signal in the `switch-case` condition, we could achieve that more programmatically.

> By looking at how Inkscape does this task, I discovered that scaling, rotating and moving are always relative to a "pivot" point, that depends on which nob are you selecting.

Yes, the use of a pivot point is the way to go. This will also help us for future implementation like "resize from center while holding <lbd>SHIFT</kbd>" and things like this.

> In the end, we can have different Models for the Canvas items, in order to abstract the Goo.CanvasItem to suit our needs better.

Also yes, and that's what I tried to do in #226 by extending directly the `Goo.CanvasRect` to create the Nob.
One thing really important here is defining a list of panels to show/hide based on the selected item. An ellipse element doesn't have a border radius property, so that sidebar panel should be hidden. Having the ability to adapt the UI based on what the user is currently interacting with is very important.

I think this is a great starting point, and we can further discuss each implementation in the code.
If possible, I'd recommend in trying to avoid too much abstraction as the code base might get cumbersome pretty easily.

Also, and this might be hard to do, we should try to split this implementation in small PRs, avoiding a single massive PR with all the changes at once.
The bigger the PR, the harder is to review it.

**Comment by Alecaddd** [comment]
All right, #231 has landed after a quick rebase, now it's time to tackle and fix everything that it's missing.
Lots of things are broken, as we knew, and visual glitches are present, but no segfault is happening so far, and with the files nicely separated is gonna be easier to tackle issues without causing merging issues.

I will personally work on the EventBus to make it more modular and remove the `switch-case` condition.
@giacomoalbe and @albfan, let's write here the things we decide to work on and open draft PRs so we can quickly go through everything that it's missing/no working, and optimize this new modular approach.

**Comment by giacomoalbe** [comment]
Good!

> I will personally work on the EventBus to make it more modular and remove the switch-case condition.

That's nice. I could suggest two different approaches, since I've already thought about that during the `canvas-split` quest :) The first is to call directly the signals with the proper arguments whenever needed. This way there's no need to update the `switch-case` in the `emit` function and so the problem is gone. But the we'd lost the ability to have a central place for "control", logging and history management, which is quite important. 

The second approach would be to use the emit function only and to pass arguments as _variable arguments_ (with the threee dots `...`). Then on signal emission we need to programmatically get the signal name from the string represenation (like `focus-on-canvas` needs to be resolved to the signal focus_on_canvas ()_) and we simply need to pass the `va_list` to the signal itself. This might cause wrong wrong argument signals' call, though, so we need extra validation. 

Just my 2 cents, I'll move them to the WIP PR when you'll open it!

> @giacomoalbe and @albfan, let's write here the things we decide to work on and open draft PRs so we can quickly go through everything that it's missing/no working, and optimize this new modular approach.

I'd like to work on the following features:
* `fill-panel` selected-item connection
* `canvas-pan` with SPACE + drag and middle mouse drag
* `selected-item` scale with transformations instead of width/height adjustment and translations (this leads to graphical glitches)
* Better integration between transform panel & selected item (add lock-ratio to CanvsaItem properties, improve fields loading and property update, others)

I'll create a new Draft PR for each one of those integrations listed in here. 

After that, do you think it's more important to add the Artboard feature (ability to create them & to add items inside them, snapping, etc) or to add the multi selection and relative object transformations (sclae, move, rotate)? I will go for the most relevant of the two.

**Comment by Alecaddd** [comment]
> I'd like to work on the following features:

Thanks for taking care of these.
Just so you know, there's no need for you to work on everything if you don't have time or you're busy with other things. No need to burn yourself in doing it all :wink: 

> After that, do you think it's more important to add the Artboard feature (ability to create them & to add items inside them, snapping, etc) or to add the multi selection and relative object transformations (sclae, move, rotate)? I will go for the most relevant of the two.

Let's not go too much ahead. Let's focus on putting back the application at the state it was before.
After that, we can regroup and organize our tasks.

**Comment by Alecaddd** [comment]
Closing this since #231 landed.
