### ISSUE TITLE
Image import dialog doesn't remember last opened folder

### ISSUE THREAD

**Issue by Alecaddd** [akiraux/Akira#279]
After importing a new image, if you try to import another one again, the dialog doesn't open the last folder where the image was imported.
I tried to use `set_current_folder()` but it didn't work.
@bilelmoussaoui do you have time to take a look at this?

**Comment by albfan** [comment]
It should work: https://valadoc.org/gtk+-3.0/Gtk.FileChooserDialog.html

Any open WIP PR

**Comment by albfan** [comment]
Uy

**Comment by Alecaddd** [comment]
I didn't have time to open a WIP PR.
Feel free to tackle it if you want to 😊

**Comment by bilelmoussaoui** [comment]
I can fix it this evening

**Comment by Alecaddd** [comment]
@bilelmoussaoui did you find time to work on this?

**Comment by bilelmoussaoui** [comment]
I just looked at this, the reason why we don't remember the path is that we use the portal to open the files. The portal doesn't give us the file location but it mounts it temporary somewhere. Hence we can't really get the path back again.

In order to fix that, we will have to open a hole in the sandbox to access home for our flatpak build and switch back to a simple GtkFileChooserDialog. Usability is much important in a design app

**Comment by bilelmoussaoui** [comment]
I have a patch for that, but we are using a new granite version now so I have to update the BaseApp first
