### ISSUE TITLE
object names are not visible 

### ISSUE THREAD

**Issue by msooraj9452** [akiraux/Akira#316]
object names are not visible in the side panel

## Screenshots of the Problem
[Link To screenshot](https://drive.google.com/file/d/12g4329LT8fX2yvieCB2wD9roGyI-Rg_U/view?usp=sharing)

- Akira Version: Beta
- OS Info: Linux mint Xfce 19.3

**Comment by Alecaddd** [comment]
That's a GTK css issue due to your desktop environment, that's why we will ship Akira with the elementary CSS theme baked into it.
You can install it by running the code from Gnome Builder, which recognizes the flatpak manifest and installs all the necessary dependencies, or get it from the Snap edge channel.
Also, Akira is not even in alpha version, so it's pretty normal to be broken :smile:
