### ISSUE TITLE
Akira should use systems GTK theme, not enforce some specific one

### ISSUE THREAD

**Issue by Tids** [akiraux/Akira#318]
Akira right now seems to enforce elementary look. From my knowledge it is not an elementary, but a general GTK app, so should act by itself like one and not go for a specific GTK- and Icon theme.

**Comment by Alecaddd** [comment]
We discussed a lot about this approach since the beginning of the project and we decided to enforce the elementary OS theme for many reasons.
The most obvious are:
* Ability to fully control the UI and UX of the application on every platform.
* Offer a consistent user experience to everyone.
* Remove the burden of supporting a million different DEs and Themes.
* Keep the focus on the architecture instead of spending time fixing themes issues.
