### ISSUE TITLE
Why keep the program focused solely on ElelentaryOS style ?

### ISSUE THREAD

**Issue by Qik000** [akiraux/Akira#350]
Why keep the program focused solely on ElelentaryOS ? It uses a DE that isnt very populat outside of Eelementary, and this will create an inconsistency for the vast majority of users, who run KDE, GNOME, XFCE and other more popular DEs.

**Comment by Alecaddd** [comment]
Because we're a very small team of developers and we don't have the resources to support multiple DE.
The elementary HIG are extremely well defined, and the elementary stylesheet offer the proper iconography and visual consistency that we're aiming for with Akira.

In the future, if we have resources and time, we will ship the app with other styles baked into it.
