### ISSUE TITLE
Use "O" as the keyboard shortcut for ovals

### ISSUE THREAD

**Issue by 12people** [akiraux/Akira#391]
## Expected Behavior
Press "O", start drawing an oval/ellipse.

## Current Behavior
Press "O", nothing happens.
Press "E", start drawing an oval/ellipse.

## Possible Solution
It'd be great to have "O" serve as the shortcut for drawing an oval/ellipse. Not only does the letter look like what you're drawing, making it easy to remember for all languages, but it's also the standard keyboard shortcut for drawing an oval in [Sketch](https://www.sketch.com/docs/shortcuts/#inserting-layers) and [Figma](https://help.figma.com/hc/en-us/articles/360040450133-Using-Shape-Tools#h_5edec1f1-055a-46d0-b1ed-1e67d76e5532).

## Context
I've been playing around with Akira today and, coming from Sketch and Figma (I use both), I just couldn't get used to the "E" shortcut for ovals.

## Your Environment
- Akira Version: v0.0.1-alpha - alpha

**Comment by Alecaddd** [comment]
Hi, thanks for trying Akira.

I'm not sure about this since our item is called "Ellipse" which is actually mathematically correct for what we're creating.
Changing the shortcut to "O" would mean changing the name of the item and the class to "Oval".

I understand the argument of muscle memory from other applications, but the fact that others do it that way it doesn't mean is the "correct" approach.
Also, both Inkscape and Gimp reference that shape as Ellipse and use the "E" shortcut.

**Comment by 12people** [comment]
Oh, okay, that makes sense to me. I can see how shortcut compatibility with the other open-source tools would be useful as well.
