### ISSUE TITLE
Position of new artboard at around 50000, 50000

### ISSUE THREAD

**Issue by der-On** [akiraux/Akira#461]
## Expected Behavior
I create a new artboard and place it on the canvas.
The artboard position is somewhere near the origin of 0,0.

## Current Behavior
I create a new artboard and place it on the canvas.
The artboard position is somewhere near 50000, 50000.
When I enter 0,0 into the position the artboard disappears and there is no way of  zooming to it on the canvas anymore.

## Possible Solution
Put canvas view at 0,0 at startup/new file.

## Steps to Reproduce (for bugs)
1. Open Akira
2. Hit A to create a new artboard
3. Create the artboard
4. Check artboard position

## Screenshots of the Problem

![akira_position_bug](https://user-images.githubusercontent.com/359399/102488235-076a8880-406c-11eb-8eb5-b2c62f97c882.png)

## Your Environment (for bugs)

- Akira Version: latest master/edge from 2020-11-01 from snapcraft.io (smae behaviour with flatpak version)
- OS Info: Ubuntu 20.04 64bit with Gnome 3

**Comment by Alecaddd** [comment]
The default canvas of Akira is a 10k by 10k pixels scrollable area, which is centered on startup to allow scrolling in multiple directions. That's why when you create an Artboard it's at 50k+ location.
If you put it at 0, it sticks to the far top left of the entire canvas. You can zoom out and scroll all the way to the top left to find it.

I'm working on implementing a "move focus on selected items" to quickly move the canvas to a selected object.

This is not an issue as this is done by design as we want an "infinite" canvas always centered with plenty of space in both directions to support LTR and RTL.

**Comment by der-On** [comment]
@Alecaddd Thanks for clarifying.
