### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by matty0blake** [akiraux/Akira#484]
## unExpected Behavior

- Akira Version:  latest by now 
- OS Info: kali linux

**Comment by Alecaddd** [comment]
I guess this is to say that the text tool doesn't work.
We know that since this is an alpha and we haven't implemented it yet. 
You can check #358 to read the full list of features we're working on.

For the future, you should write a better issue, with proper description of the problem, screenshots, and all the info you can to help us identify the problem.
Just like the template suggests.
