### ISSUE TITLE
Cannot build, missing goocanvas-3.0

### ISSUE THREAD

**Issue by plonibarploni** [akiraux/Akira#486]
## Expected Behavior
Run `ninja` and Akira will build

## Current Behavior
It fails with this error:
```
Run-time dependency goocanvas-3.0 found: NO (tried pkgconfig and cmake)

../meson.build:21:0: ERROR: Dependency "goocanvas-3.0" not found, tried pkgconfig and cmake
```

## Context
I have a script that pulls updates whenever the Akira repo has newer commits and attempts to rebuild it.
For some time already (I'm not sure how long), it has been failing to rebuild with the above error.
I have attempted to find the correct package by searching around but I could not find it.

- Akira Version: git master
- OS Info: Ubuntu 20.10

**Comment by Alecaddd** [comment]
We updated the dev documentation to report this change: https://github.com/akiraux/Akira/blob/master/CONTRIBUTING.md#getting-started

GooCanvas 3 hasn't been released tot he official PPA so you need to manually install it on your system.
This issue is only for users who build from source as that library is baked into the flatpak release.
