### ISSUE TITLE
Better redesigned export dialog

### ISSUE THREAD

**Issue by Suzie97** [akiraux/Akira#535]
I was browsing through the Glimpse-NX project and found this issue regarding the export dialog. I think they mention some good points. https://github.com/glimpse-editor/glimpse-nx-design/issues/7#issue-747226185

As mentioned in that issue, exporting is a very common task and should be very fast and easy.

In the current implementation of the export dialog in akira, the user needs to select the path manually (by default it sets to home, which I don't think is very useful. The photos directory might be a better choice). Also, akira uses a Gtk.ComboBox to select the export formats (PNG, JPG). 

I think that the format chooser should be replaced by a Gtk.StackSwitcher showing all the available exports with an other button for the more obscure ones, 

These are the designs proposed by the Glimpse-NX designers and akira can do something similar to this:

![Screenshot from 2021-03-31 08-35-34](https://user-images.githubusercontent.com/68198116/113084737-39a78c80-91fc-11eb-9e34-7cfc24448072.png)

![Screenshot from 2021-03-31 08-35-48](https://user-images.githubusercontent.com/68198116/113084778-4e842000-91fc-11eb-9457-fde56ecb99ee.png)

Oh yeah, I almost forgot. When the export button is clicked, Akira can just use a popup rather than opening a separate Export dialog. When the settings button on the export pop up is clicked, then a separate dialog with advanced options can be displayed.

What do the devs think about this??

**Comment by Alecaddd** [comment]
Hi thank you so much for your interest in Akira and for your suggestions.
Some of the things you propose are interesting, others not so much as they create extra steps that are not really necessary.

The current export dialog is only a first implementation of the much more powerful and flexible exporting capabilities we will implement in Akira.

Each Artboard, group, or single item, will have a dedicated Export section at the bottom of the Options sidebar, similar to what Figma and Sketch have.
That section will look similar to what you propose, with a more compact UI of options and it won't require the opening of any dialog.

The current dialog is intended to be used when exporting needs more control and fine tuning.
The GTK StackSwitcher wouldn't work very well due to the limited space and all the format we will implement.
The dialog also offers a preview of the image that will be exported, allowing the user to see how the compression affects the final image.
The dialog will also allow exporting multiple items at once, allowing users to control the file name and format of multiple selected objects to do a batch export.

The dialog also will remember the latest used settings, so the user won't need to change anything if the export options and location don't need to change.

**Comment by Suzie97** [comment]
> 
> 
> Hi thank you so much for your interest in Akira and for your suggestions.
> Some of the things you propose are interesting, others not so much as they create extra steps that are not really necessary.
> 
> The current export dialog is only a first implementation of the much more powerful and flexible exporting capabilities we will implement in Akira.
> 
> Each Artboard, group, or single item, will have a dedicated Export section at the bottom of the Options sidebar, similar to what Figma and Sketch have.
> That section will look similar to what you propose, with a more compact UI of options and it won't require the opening of any dialog.
> 
> The current dialog is intended to be used when exporting needs more control and fine tuning.
> The GTK StackSwitcher wouldn't work very well due to the limited space and all the format we will implement.
> The dialog also offers a preview of the image that will be exported, allowing the user to see how the compression affects the final image.
> The dialog will also allow exporting multiple items at once, allowing users to control the file name and format of multiple selected objects to do a batch export.
> 
> The dialog also will remember the latest used settings, so the user won't need to change anything if the export options and location don't need to change.

Thank you so much for the reply. 

I think that having a separate export section like in sketch addresses the issues that I have mentioned. And opening up a separate export dialog for more control is also a great idea. 

Another question: Are you gonna include the option to choose the export location in the export section? Because, Figma doesn't have one and while exporting, it opens up a FileChooserDialog and that introduces just a little of friction to the process.
