### ISSUE TITLE
Feature Request: Use docker

### ISSUE THREAD

**Issue by Abdallah-Moh** [akiraux/Akira#606]
## Expected Behavior
Use docker to make it easy for new contributors to contribute instead of wasting time installing packages and having packages not latest on some distros

## Current Behavior
wasting time installing

## Possible Solution
Use Docker

**Comment by albfan** [comment]
Adding another stack to the pile is probably the opposite of easing the development, but if you have a temptative example like https://medium.com/@SaravSun/running-gui-applications-inside-docker-containers-83d65c0db110 (see how many low level details you have to care of)

We probably can discuss how docker will get in the way.

You can use flatpak if you don't want to bother with dependencies (still not ideal)

Probably a more actionable issue will contain a problem, instead of a solution to a blurry problem (get dependencies)

What's your pain about getting the dependencies?

**Comment by Alecaddd** [comment]
@Abdallah-Moh Please, don't offer suggestion you have no idea about.
You clearly don't know how Docker works and how to use it for building local applications.

Also 
> wasting time installing

It's not a valid issue report.

Closing this as I 100% agree with Alberto.

**Comment by LucileDT** [comment]
I will add that I had to create/maintain a local environment for development purpose using Docker on several previous projects, it is always a pain to create it and to maintain it... if Docker had better error/debugging messages, I would definitively agree with @Abdallah-Moh, but it doesn't.

If a Docker wizard come one day in this project, why not, but with the current team, the cost of creating this environment is too high.
