### ISSUE TITLE
window is too small

### ISSUE THREAD

**Issue by oussamabouchareb** [akiraux/Akira#617]
## Expected Behavior

the window should be full screen by default in i3wm

## Current Behavior

the window is smaller than it should be, and for some reason my background image doesn't show when the window isn't full screen instead it shows my background as black and when you hit the resize button nothing happens

## Possible Solution

if I had to take a guess the window is probably set to have a specific height and width when launched that doesn't take into account that tiling window managers exist, making the height automatic or adapts to the existing window height and width would probably fix it.

## Steps to Reproduce (for bugs)

1. use ubuntu with i3wm
2. install akira from snapstore
3. open akira from dmenu

## Context

my usable screen space is eaten up because of how small the actual usable window is

## Your Environment (for bugs)

- Akira Version: v0.0.13 - alpha
- OS Info:
OS: Ubuntu
kernel version: 5.4.0-77-generic
OS version: 20.04.2

**Comment by oussamabouchareb** [comment]
and idk if relevant but my settings seem to not function either, like I can't switch to dark mode or do anything in settings

**Comment by albfan** [comment]
Probably screenshots and/or screencast will explain this better

**Comment by Abdallah-Moh** [comment]
@oussamabouchareb Can you provide us with more info ?

**Comment by Alecaddd** [comment]
The snap package is outdated and not supported anymore (I'll probably remove it soon).
Please, try the flatpak installation.
Also, unfortunately we don't currently support `i3` Window manager as we don't have the resources for it.
Marking this as out of scope.

**Comment by oussamabouchareb** [comment]
> The snap package is outdated and not supported anymore (I'll probably remove it soon).
> Please, try the flatpak installation.
> Also, unfortunately we don't currently support `i3` Window manager as we don't have the resources for it.
> Marking this as out of scope.

I understand, good luck with your project, but may I ask why you no longer support snap if that's ok?

**Comment by Alecaddd** [comment]
Sure, you can ask anything you want :smile: 

We don't have a Snap maintainer in the core team and no one seems to be able to handle the building dependencies and process necessary to solve all the problems that arise since the first snap release.
I tried requesting support in the Snap forum and from other Snap devs but months have passed without any help.
So, rather than keep releasing a broken package, I'm considering removing it for now and only release via flatpak, since we active have Flatpak maintainers that can quickly fix any potential issue.

If you or anyone you know is a Snap developer willing to help us out, I'd be more than happy to reopen these issues and keep publishing it.
