### ISSUE TITLE
[suggestions] adopt GTK4 instead of GTK3..!!!!

### ISSUE THREAD

**Issue by HarshilPatel007** [akiraux/Akira#632]
Hi devs,
Great to see akira's progress. I've seen akira uses GTK3 at this moment. I'd like to suggest migrate to/adopt GTK4, as this project is at it's early stage. So, It'll be a easy task. GTK4 comes with a great improvements. So, why wouldn't we harness the power of GTK4..???? If this project grows, then it'll be a huge pain to migrate it to gtk4 later. If wwe adopt GTK4 from now, then in future we can focus on adding new features instead of migration process. (this is what GIMP is facing this problem right now.)

**Comment by Alecaddd** [comment]
Hi, and thanks for your interest in Akira.

> I'd like to suggest migrate to/adopt GTK4, as this project is at it's early stage. 

We won't do it for now as our main target are X11 based distributions that still run GTK3.
Also, GTK4 is not entirely completed, with widgets and bindings not yet available.

> If this project grows, then it'll be a huge pain to migrate it to gtk4 later

Not really as we're very careful in keeping the UI separated and independent from the core Canvas library, which is the most complex part of the application.

> this is what GIMP is facing this problem right now.

Not entirely true as GIMP was stuck in the migration between GTK2 and GTK3. That is fairly complicated since the API drastically changed between those 2 version.
If you look at the documentation, the differences between GTK3 and GTK4 are sometimes minimal, with some widgets being almost identical.

We will upgrade to GTK4 once it's more spread and widely available out of the box in all major distros.
