### ISSUE TITLE
Akira does not enters Dark Mode!

### ISSUE THREAD

**Issue by omegaui** [akiraux/Akira#691]
Hi!
**I built Akira from source**
These are my system specs
![Screenshot from 2022-01-01 15-01-13](https://user-images.githubusercontent.com/73544069/147847849-2739c074-9b3d-40b0-ad8d-dd14cf29134f.png)

**Even after Enabling the Dark Mode from here and restarting Akira, 
It doesn't enters Dark Mode!**

![Screenshot from 2022-01-01 15-02-33](https://user-images.githubusercontent.com/73544069/147847863-3ce2a954-0bf0-4931-854d-366f09bd91e5.png)

I also tried launching from terminal **to see if there are any exception** but **nothing** could be seen ...
![Screenshot from 2022-01-01 15-02-22](https://user-images.githubusercontent.com/73544069/147847906-ebf17dfe-179f-420e-a849-ea6927532a01.png)

It just cannot enter dark mode!
![Screenshot from 2022-01-01 15-02-35](https://user-images.githubusercontent.com/73544069/147847885-593b2224-e239-4e3f-9f74-d768d5a87072.png)

**Comment by albfan** [comment]
Yours is not last version of akira, so, how did you install Akira?

Notice "Follow the system theme variation"

![Captura de pantalla de 2022-01-01 12-21-04](https://user-images.githubusercontent.com/220968/147849421-882d5e0d-756d-4990-9749-ce8289d1b391.png)

**Comment by omegaui** [comment]
> Yours is not last version of akira...

I just did a got clone and built it yesterday only.

**Comment by Alecaddd** [comment]
@omegaui If you're not planning to develop Akira, I'd recommend installing it via flatpak as it's better integrated with the stylesheet.
If you build from source in distros other than elementary OS, you will need to manually install the elementary OS stylesheet and icon theme to get the correct UI, as well as dark mode variation.

If you're interested in developing it, be aware that the `master` branch is currently stale as we're focused on the `main` branch, in which we're slowly rebuilding the UI.
Closing this as it's not relevant since we don't support other distros outside the flatpak release.

**Comment by bigfatbird** [comment]
@Alecaddd Maybe you should switch the default branch in the settings from master to main, as when you visit the page you will be shown the master branch

**Comment by Alecaddd** [comment]
Not yet, the `main` branch is in a very WIP state and lot of the UI is completely missing.
I will switch it once we're at a comparable state with `master`.

**Comment by bigfatbird** [comment]
Ah ok. Sorry, thought you weren’t aware of that

Von meinem iPhone gesendet
