### ISSUE TITLE
Build and Test

### ISSUE THREAD

**Issue by aliuadepoju** [akiraux/Akira#77]
How can i build and test on Ubuntu?

**Comment by e200** [comment]
Same here.

**Comment by f0s3** [comment]
How can I build this project to develop and contribute to it?

**Comment by Brekmister** [comment]
Random developer strolling by, I took the liberty of experimenting a little bit. I got it to build on clean installs of Ubuntu under VM's as well as directly on my rig running Fedora 29 Workstation (Will do more experimentation on that)

So, I made a little process here to build Akira. Feel free to let me know if there needs any clarification.

# Process of cloning, building and installing
 1. Make sure system is up to date, you probably want to run this inside a VM (Virtualbox, Gnome Boxes, etc) or a machine that you just don't really care about since it will install the incomplete app and AFAIK, there isn't a easy way to uninstall it. Will update if I do find a way.
 2. Install dependencies `sudo apt update && sudo apt install ...` (See below)
 3. Choose where you want to put the source files, you don't need it's own folder as Git clone will do that for you. `cd` into that.
 4.  Clone and cd into it, `git clone https://github.com/akiraux/Akira/`, `cd Akira`
 5. `meson build --prefix=/usr`
 6. `cd build`
 7. `ninja && sudo ninja install`
 8. You will now find Akira installed in your programs :)

## Required packages for Ubuntu 18.04 and 18.10
(This is coming from a vanilla and minimal Desktop install, I have not tested any derivatives)
 - `git`
 - `libgtk-3-dev`
 - `libxml2-dev`
 - `libxml2-utils`
 - `libgtksourceview-3.0-dev`
 - `libclutter-1.0-dev`
 - `libclutter-gtk-1.0-dev`
 - `valac`
 - `meson`

I am also going to look into dependencies for Debian, CentOS, RedHat and, Fedora as well. Maybe Ill make a pull request for a `Dependencies` branch for now. Throw it into the README.md or a BUILDING.md file (Let me know if there is a preference)

**Comment by albfan** [comment]
Or maybe you can just use flatpak: 

https://github.com/akiraux/Akira/tree/wip/albfan/flatpak?files=1

and start hacking in 5 min

**Comment by Brekmister** [comment]
Ill pass. 

Flatpak is great and all but, it's also nice to have these built natively using tools already built into the OS. And see how it actually behaves when you put it as a RPM or DEB using the libraries built into these distros.

Personal preference.

**Comment by Alecaddd** [comment]
The list of dependencies and how to install it is written in the readme file of this repo.
As suggested by @albfan, an easy to test flatpak is available for anyone who's not comfortable manually installing dependencies and building with meson.
