### ISSUE TITLE
Left Panel: Create Transform Box

### ISSUE THREAD

**Issue by Alecaddd** [akiraux/Akira#89]
Reference UI Mockup:
![transform-box](https://user-images.githubusercontent.com/2527103/53469505-0853a580-3a13-11e9-9c99-7507dbcc224a.png)

**Comment by BaptisteGelez** [comment]
Hello! I would like to help on this issue, if possible. :slightly_smiling_face: I just have one question: should I create a new widget for the letter + input groups (so that we can just do `new GroupedInput(new Gtk.Label("X"), x_pos_input)`)?

(also, is there a Matrix or Gitter room so that I can ask other questions more easily if needed?)

Thank you!

**Comment by bilelmoussaoui** [comment]
@BaptisteGelez Having a widget for this would be nice! You don't need to pass a Gtk.Label as a parameter, just a string is enough. 

> (also, is there a Matrix or Gitter room so that I can ask other questions more easily if needed?)`

We will have some news to share about that soon!
